#include <jni.h>
#include "android/log.h"
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dobong_taskbar_TaskBarService */

#ifndef _Included_com_dobong_taskbar_TaskBarService
#define _Included_com_dobong_taskbar_TaskBarService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dobong_taskbar_TaskBarService_UPDATE_TICK
#define com_dobong_taskbar_TaskBarService_UPDATE_TICK 300L
#undef com_dobong_taskbar_TaskBarService_NUM_MAX_TASK
#define com_dobong_taskbar_TaskBarService_NUM_MAX_TASK 10L
#undef com_dobong_taskbar_TaskBarService_POSITION
#define com_dobong_taskbar_TaskBarService_POSITION -500L
#undef com_dobong_taskbar_TaskBarService_DRAG_Y
#define com_dobong_taskbar_TaskBarService_DRAG_Y 10L
/*
 * Class:     com_dobong_taskbar_TaskBarService
 * Method:    getAppList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dobong_taskbar_TaskBarService_getAppList
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

JNIEXPORT void JNICALL Java_com_dobong_taskbar_TaskBarService_getAppList(JNIEnv *env, jobject obj)
{
	jint i;
	jint size;
	jclass cls = (*env)->GetObjectClass(env, obj);

	//	jfieldID fid = (*env)->GetFieldID(env, cls, "am", "Landroid/content/ActivityManager;");
	//	jobject am = (*env)->GetObjectField(env, obj, fid);

	// 우선 클래스를 얻어 옴.
	jclass clsActivityManager = (*env)->FindClass(env, "android/app/ActivityManager");
	jclass clsArrayList = (*env)->FindClass(env, "java/util/ArrayList");
	jclass clsContext = (*env)->FindClass(env, "android/content/Context");
	jclass clsRunningTaskInfo = (*env)->FindClass(env, "android/app/ActivityManager$RunningTaskInfo");
	jclass clsList = (*env)->FindClass(env, "java/util/List");
	jclass clsComponentName = (*env)->FindClass(env, "android/content/ComponentName");

	// MethodID를 구함.
	jmethodID mGetSystemService = (*env)->GetMethodID(env, cls, "getSystemService", "(Ljava/lang/String;)Ljava/lang/Object;");
	jmethodID mArrayListCtor = (*env)->GetMethodID(env,  clsArrayList, "<init>", "()V");
	jmethodID mArrayListCtor2 = (*env)->GetMethodID(env,  clsArrayList, "<init>", "(Ljava/util/Collection;)V");
	jmethodID mAdd = (*env)->GetMethodID(env, clsArrayList, "add", "(Ljava/lang/Object;)Z");
	jmethodID mAdd2 = (*env)->GetMethodID(env, clsArrayList, "add", "(ILjava/lang/Object;)V");
	jmethodID mContains = (*env)->GetMethodID(env, clsArrayList, "contains", "(Ljava/lang/Object;)Z");
	jmethodID mGetRunningTasks = (*env)->GetMethodID(env, clsActivityManager, "getRunningTasks", "(I)Ljava/util/List;");
	jmethodID mIsEmpty = (*env)->GetMethodID(env, clsList, "isEmpty", "()Z");
	jmethodID mSize = (*env)->GetMethodID(env, clsList, "size", "()I");
	jmethodID mGet = (*env)->GetMethodID(env, clsList, "get", "(I)Ljava/lang/Object;");
	jmethodID mGetPackageName = (*env)->GetMethodID(env, clsComponentName, "getPackageName", "()Ljava/lang/String;");

	// fieldID를 구함.
	jfieldID field_topActivity = (*env)->GetFieldID(env, clsRunningTaskInfo, "topActivity", "Landroid/content/ComponentName;");
	jfieldID field_ACTIVITY_SERVICE = (*env)->GetStaticFieldID(env, clsContext, "ACTIVITY_SERVICE", "Ljava/lang/String;");
	jfieldID field_mActive = (*env)->GetFieldID(env, cls, "mActive", "Ljava/lang/String;");
	jfieldID field_mAppList = (*env)->GetFieldID(env, cls, "mAppList", "Ljava/util/ArrayList;");

	// 객체를 생성자를 호출하여 생성함..	

	// ArrayList의 객체를 생성.
	jobject activity = (*env)->GetStaticObjectField(env, clsContext, field_ACTIVITY_SERVICE);
	jobject am = (*env)->CallObjectMethod(env, obj, mGetSystemService, activity);
	jobject appList = (*env)->CallObjectMethod(env, am, mGetRunningTasks, com_dobong_taskbar_TaskBarService_NUM_MAX_TASK);

	jobject newList = (*env)->NewObject(env, clsArrayList, mArrayListCtor);
	jobject result = (*env)->NewObject(env, clsArrayList, mArrayListCtor);
	jobject temp;


	(*env)->MonitorEnter(env, obj);

	if((*env)->CallBooleanMethod(env, appList, mIsEmpty)) {
		jstring str = (*env)->NewStringUTF(env, "");
		(*env)->SetObjectField(env, obj, field_mActive, (jobject)str);
	}
	else {
		jobject temp1 = (*env)->CallObjectMethod(env, appList, mGet, 0);
		jobject temp2 = (*env)->GetObjectField(env, temp1, field_topActivity);
		jobject temp3 = (*env)->CallObjectMethod(env, temp2, mGetPackageName);
		(*env)->SetObjectField(env, obj, field_mActive, temp3);
	}

	(*env)->MonitorExit(env, obj);


	size = (*env)->CallIntMethod(env, appList, mSize);
	for (i = 0 ; i < size; ++i){
		jobject temp1 = (*env)->CallObjectMethod(env, appList, mGet, i);
		jobject temp2 = (*env)->GetObjectField(env, temp1, field_topActivity);
		jobject temp3 = (*env)->CallObjectMethod(env, temp2, mGetPackageName);

		(*env)->CallBooleanMethod(env, newList, mAdd, temp3);
	}

	(*env)->MonitorEnter(env, obj);
	jobject mAppList = (*env)->GetObjectField(env, obj, field_mAppList);
	temp = (*env)->NewObject(env, clsArrayList, mArrayListCtor2, mAppList);
	(*env)->MonitorExit(env, obj);

	size = (*env)->CallIntMethod(env, temp, mSize);
	for(i = 0 ; i < size; ++i)
	{
		jobject str = (*env)->CallObjectMethod(env, temp, mGet, i);
		if((*env)->CallBooleanMethod(env, newList, mContains, str)) {
			(*env)->CallBooleanMethod(env, result, mAdd, str);
		}
	}

	size = (*env)->CallIntMethod(env, newList, mSize);
	for(i = 0 ; i < size; ++i)
	{
		jobject str = (*env)->CallObjectMethod(env, newList, mGet, i);
		if(!((*env)->CallBooleanMethod(env, result, mContains, str))) {
			(*env)->CallVoidMethod(env, result, mAdd2, 0, str);
		}
	}

	(*env)->MonitorEnter(env, obj);
	(*env)->SetObjectField(env, obj, field_mAppList, result);
	(*env)->MonitorExit(env, obj);
}



/*
private void getAppList()
{
        ActivityManager am = (ActivityManager)getSystemService(Context.ACTIVITY_SERVICE);
        List<RunningTaskInfo> appList = am.getRunningTasks(NUM_MAX_TASK);
        ArrayList<String> newList = new ArrayList<String>();
        ArrayList<String> result = new ArrayList<String>();
        ArrayList<String> temp;
        if(appList.isEmpty()) mActive = "";

        else mActive = appList.get(0).topActivity.getPackageName();

        for(int i = 0; i < appList.size(); ++i)
        {
                newList.add(appList.get(i).topActivity.getPackageName());
        }

        synchronized(this)
        {
                temp = new ArrayList<String>(mAppList);
        }

        for(String str : temp)
        {
                if(newList.contains(str)) result.add(str);
        }

        for(String str : newList)
        {
                if(!result.contains(str)) result.add(str);
        }

        synchronized (this)
        {
                mAppList = result;
        }
}*/

